version: '3.11'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672" # for AMQP protocol port
      - "15672:15672" # for management site port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
